name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - 'environments/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, prod]

    env:
      AWS_REGION: usw-1
      TF_VAR_org: hexe

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ matrix.environment == 'prod' && '222222222222' || '111111111111' }}:role/TerraformRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init -backend-config="key=${{ matrix.environment }}/terraform.tfstate"

    - name: Terraform Plan
      run: terraform plan -var-file=environments/${{ matrix.environment }}/terraform.tfvars

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var-file=environments/${{ matrix.environment }}/terraform.tfvars
